clicknetapp/urls.py
from django.conf.urls import url
from django.urls import path
from .import views

urlpatterns = [
    path("",views.home,name="home"),
    # path("home/",views.home,name="home"),
    path("logout/",views.logout,name="logout"),
    path("profile/",views.profile,name = 'profile'),
    path("payout_rate/",views.payout_rate,name="payout_rate"),
    path("privacy_policy/",views.privacy,name="privacy"),
    path("terms/",views.terms,name="termsofus"),
    path("login/",views.log_in,name="login"),
    path("signup",views.signup,name="signup"),
    url(r'^activate/(?P<rendom>[0-9a-zA-Z]+)/(?P<uidb64>[0-9a-z]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    path('resend_email/',views.resend_email,name='resend_email'),
    path("dashboard/",views.dashboard,name = "dashboard" ),
    path('account/',views.account,name = 'account'),
    path('shorturladmin/',views.shorturladmin,name='shorturladmin'),
    path('shorturl/',views.shorturl,name='shorturl'),
    path("myurls/",views.myurls,name="myurls"),
    path("createchart/",views.createchart,name="createchart"),
    path("geturl/",views.geturls,name="geturl"),
    path("refresh/",views.refresh,name="refresh"),
    path("refer/",views.refer,name="refer"),
    path("myteam/",views.myteam,name="myteam"),
    path("forgot_password/",views.forgot_password,name="forgot_password"),
    path("paymentstatus/",views.paymentstatus,name="paymentstatus"),
    path('redeem/',views.redeem,name = 'redeem'),
    path('adminarea/',views.adminarea,name = 'adminarea'),
    path('adminlogin/',views.adminlogin,name = 'adminlogin'),
    path('success/<int:id>/',views.redeemsuccess),
    path('block/<int:id>/',views.block),
    path('cancel/<int:id>/',views.redeemcancel),
    path('getip/',views.getip,name='getip'),
    path('contactmsg',views.contactmsg),
    path('getip/',views.getip),
    path('<str:code>/',views.get_url),
    
    path('forgot/password/<str:key>/',views.forgot_password_user),
    path('<int:id>/delete',views.delete),

]

net/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('clicknetapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clicknetapp/models.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from datetime import timedelta
# Create your models here.

class usertab(models.Model):
    username = models.CharField(max_length=500)
    email = models.CharField(max_length=500)
    password = models.CharField(max_length=500)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_block = models.BooleanField(default=False)
    refercode = models.CharField(max_length=500)
    referredby = models.CharField(null=True,max_length=500)
    img = models.ImageField(upload_to='user_img',default='user_img/default.png')



class noti(models.Model):
    title = models.CharField(max_length=36)
    body = models.CharField(max_length=120)
class balance(models.Model):
    user = models.ForeignKey(usertab,on_delete = models.CASCADE)
    blc = models.FloatField(default=0)
    referblc = models.FloatField(default=0)
    referbyblc = models.FloatField(default=0)
class payment(models.Model):
    brand = models.CharField(max_length=150)
class userurltable(models.Model):
    url = models.URLField(max_length=400)
    shorturl = models.URLField(max_length=5000,null=True)
    click = models.IntegerField(default=0)
    earning = models.FloatField(default=0)
    user = models.ForeignKey(usertab,on_delete = models.CASCADE,null=True)
class redeemtable(models.Model):
    def indiantime():
        return now() + timedelta(minutes = 330)
    user = models.ForeignKey(usertab,on_delete = models.CASCADE)
    paymentmode = models.ForeignKey(payment,on_delete=models.CASCADE)
    paddress = models.CharField(max_length=120)
    ifsc = models.CharField(max_length=120,null=True)
    amount = models.CharField(max_length=120)
    redeem_date = models.DateTimeField(default=indiantime )
    status = models.IntegerField(default=0)



class useraddress(models.Model):
    name = models.CharField(max_length=120)
    adr = models.CharField(max_length=120)
    state = models.CharField(max_length=120)
    zip = models.CharField(max_length=120)
    phone = models.CharField(max_length=120)
    user = models.ForeignKey(usertab,on_delete = models.CASCADE)
class codetable(models.Model):
    code = models.CharField(max_length=150)
class iptable(models.Model):
    ip = models.CharField(max_length=500)
    cookie = models.CharField(max_length=100,null=True)
    created_date = models.DateTimeField(default=now)

class static(models.Model):
    def indiantime():
        return now() + timedelta(minutes = 330)
    user = models.ForeignKey(usertab,on_delete = models.CASCADE)
    date = models.DateTimeField(default=indiantime )
    click = models.IntegerField(default=0)

class statictab(models.Model):
    def indiantime():
        date = now() + timedelta(minutes = 330)
        return date.date()
    user = models.ForeignKey(usertab,on_delete = models.CASCADE)
    date = models.DateField(default=indiantime)
    click = models.IntegerField(default=0)

class password_change(models.Model):
    user = models.ForeignKey(usertab,on_delete = models.CASCADE)
    key = models.CharField(max_length=128)

# class test(models.Model):
#     user = models.ForeignKey(usertab,on_delete = models.CASCADE)
#     key = models.CharField(max_length=128)

clicknetapp/views.py
from django.shortcuts import render, redirect
from clicknetapp.models import *
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib import auth
from django.conf import settings
from django.utils.crypto import get_random_string
from .tokens import account_activation_token
from django.contrib.auth import authenticate
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from urllib.parse import urlparse
from .import short_url as s
from django.utils import timezone
from datetime import timedelta
import decimal

# Create your views here.
def home(request):
    user = usertab.objects.all()
    link = userurltable.objects.all()
    allclick = 0
    for i in link:
        allclick = int(allclick) + int(i.click)
    alluser = user.count()
    alllink = link.count()
    d = {'alluser' : alluser,'alllink' : alllink,'allclick' : allclick}
    return render(request,"html/home/index.html",d)

def dashboard(request):
    if request.session.has_key('user_id'):
        clickearning = 0
        redeemsuccess = 0
        redeempanding = 0
        redeemcancel = 0
        totalclicks = 0
        obj = userurltable.objects.filter(user_id = request.session['user_id'])
        obj1 = balance.objects.get(user_id = request.session['user_id'])
        obj2 = redeemtable.objects.filter(user_id = request.session['user_id'])
        pastdate = timezone.now() - timedelta(days=9) + timedelta(minutes=330)
        nowdate = timezone.now() + timedelta(minutes=330)
        staticdata = statictab.objects.filter(date__range=[pastdate.date() , nowdate.date() ],user_id=request.session['user_id']).values()
        for data in obj:
            clickearning += decimal.Decimal(data.earning)
            totalclicks += int(data.click)
        if obj2 is not None:
            for dt in obj2:
                if dt.status == 0:
                    redeempanding += decimal.Decimal(dt.amount)
                elif dt.status == 1:
                    redeemsuccess += decimal.Decimal(dt.amount)
                else :
                    redeemcancel += decimal.Decimal(dt.amount)
        walletbalance = decimal.Decimal(obj1.blc)
        referblc = decimal.Decimal(obj1.referblc)
        totalredeem = redeemsuccess + redeempanding
        lifetimeearning = walletbalance + totalredeem
        notif = noti.objects.all()
        blc = balance.objects.get(user = request.session['user_id'])
        d1 = {"d" : notif,'blc' : blc.blc ,'totalclicks':totalclicks ,'lifetimeearning': lifetimeearning ,'totalredeem':totalredeem ,'redeemsuccess':redeemsuccess ,'redeempanding':redeempanding ,'clickearning':clickearning,'referblc':referblc,'staticdata' : list(staticdata)}
        return render(request,"html/dashboard.html",d1)
    else:
           return HttpResponseRedirect( settings.BASEURL + "login")
def payout_rate(request):
    return render(request,"html/home/payout-rate.html")
def privacy(request):
    return render(request,"html/home/privacy.html")
def terms(request):
    return render(request,"html/home/terms.html")
def log_in(request):
    if request.method == 'POST':
        uname = request.POST.get("uname")
        pwd = request.POST.get("password")
        try:
            obj = usertab.objects.get(username = uname , password = pwd)
        except:
            obj = None
        try:
            obj2 = usertab.objects.get(email = uname , password = pwd)
        except:
            obj2 = None
        if obj is not None:
            if obj.is_active == True:
                if obj.is_block == False:
                    request.session["user_id"] = obj.id
                    return HttpResponseRedirect("../dashboard")
                else:
                    d = {"error" : "Your Account Is Blocked By Click.Net Compney"}
                    return render(request,"html/home/login.html",d)
            else:
                d = {"error" : "Please verify your email address and login"}
                return render(request,"html/home/login.html",d)
        elif obj2 is not None:
            if obj2.is_active == True:
                request.session["user_id"] = obj2.id
                return HttpResponseRedirect("../dashboard")
            else:
                d = {"error" : "Please verify your email address and login"}
                return render(request,"html/home/login.html",d)
        else:
            d = {"error" : "Username and Password is invalid!"}
            return render(request,"html/home/login.html",d)
    else:
        return render(request,"html/home/login.html")
def signup(request):
    if request.method == 'POST':
        uname = request.POST.get("uname")
        email = request.POST.get("email")
        rcode = request.POST.get("refer")
        pwd = request.POST.get("password")
        rpwd = request.POST.get("re_password")
        obj1 = usertab.objects.filter(username = uname)
        obj2 = usertab.objects.filter(email = email)
        if rcode == "":
            rcode = None
        if obj1.count()>0 :
            dict_data1={'error1':'Username alrady exist please retry',"uname": uname,"email":email,"pwd":pwd,"rpwd":rpwd,'refercode':rcode}
            return render(request,"html/home/signup.html",dict_data1)
        elif obj2.count()>0 :
            dict_data2={'error2':'Email alrady exist please retry',"uname": uname,"email":email,"pwd":pwd,"rpwd":rpwd,'refercode':rcode}
            return render(request,"html/home/signup.html",dict_data2)
        elif pwd != rpwd :
            dict_data4={'error3':'Password does not match please retry',"uname": uname,"email":email,"pwd":pwd,"rpwd":rpwd,'refercode':rcode}
            return render(request,"html/home/signup.html",dict_data4)
        else:
            refer = usertab.objects.all()
            refercode = get_random_string(length=6, allowed_chars='ASDFGHJKLZXCVBNMQWERTYUIOP1234567890')
            j = 0
            while j==0:
                j+=1
                for i in refer:
                    if refercode == i.refercode:
                        refercode = get_random_string(length=6, allowed_chars='ASDFGHJKLZXCVBNMQWERTYUIOP1234567890')
                        j=0
                    else:
                        pass
            user = usertab(username = uname,email = email,password=pwd,is_active=False,referredby=rcode,refercode=refercode)
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('html/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': s.encode_url(user.id),
                'token': account_activation_token.make_token(user),
                'rendom': get_random_string(length=64, allowed_chars='qwertyuiopasdfghjklzxcvbnmASDFGHJKLZXCVBNMQWERTYUIOP1234567890')
            })
            mail_subject = 'Activate your account.'
            send_mail(mail_subject, "", "hp30405@gmail.com", [email] ,fail_silently=False,html_message=message )
            ub = balance(user = user,blc= 500)
            ub.save()
            return render(request,'html/done.html')
    else:
        data = []
        for i in usertab.objects.all():
            data.append(i)
        d = {"refer" : data}
        return render(request,"html/home/signup.html",d)

def resend_email(request):
    if request.method == 'POST':
        email = request.POST.get("email")
        try:
            user = usertab.objects.get(email = email)
        except:
            user = None
        if user is not None:
            if user.is_active == False:
                current_site = get_current_site(request)
                message = render_to_string('html/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': s.encode_url(user.id),
                    'token':account_activation_token.make_token(user),
                    'rendom': get_random_string(length=64, allowed_chars='qwertyuiopasdfghjklzxcvbnmASDFGHJKLZXCVBNMQWERTYUIOP1234567890')
                })
                mail_subject = 'Activate your account.'
                send_mail(mail_subject, "", "hp30405@gmail.com", [email], fail_silently=True ,html_message=message )
                return render(request,'html/done.html')
            else:
                d = {"error" : "you are alrady confirm your email please login","email":email}
                return render(request,"html/resendemail.html",d)
        else:
            d = {"error" : "this email is not registerd please sign up Or something went wrong","email":email}
            return render(request,'html/resendemail.html',d)
    else:
        return render(request,"html/resendemail.html")

def activate(request,rendom, uidb64, token):
    try:
        uid = s.decode_url(uidb64)
        user = usertab.objects.get(id=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist ):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, "html/emailconfirmed.html", {"user" : user} )

    else:
        return render(request, "html/emailconfirmed.1.html")
def logout(request):
    auth.logout(request)
    return redirect('login')
def profile(request):
    if request.session.has_key('user_id'):
        blc = balance.objects.get(user = request.session['user_id'])
        obj = usertab.objects.get(id = request.session['user_id'] )
        notif = noti.objects.all()
        users = usertab.objects.all()

        for i in users:
            if i.refercode == obj.referredby:
                referuser = i.username
                break
            else:
                referuser = None
        d = {"d" : notif,'blc' : blc.blc,"user" : obj,'referuser':referuser }

clicknetapp/templates/html/adminarea.html
{% extends 'html/header.html' %}
{% block head %}
<title>Admin Area</title>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="d-md-flex align-items-center">

                            <caption><h1 style="text-align:center">Payment Tabel</h1></caption><br/>


                </div>
            </div>
        </div>
    </div>
</div>
<div class="">
<table id="example" class="display nowrap" style="width:100%">
        <thead>
            <tr>
                <th>No.</th>
                <th>Username</th>
                <th>Amount</th>
                <th>Payment Address</th>
                <th>Ifsc</th>
                <th>Payment Mode</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in data %}
            <tr>
                <td></td>
                <td>{{ i.user.username }}</td>
                <td>{{ i.amount }}</td>
                <td>{{ i.paddress }}</a></td>
                <td>{{ i.ifsc }}</a></td>
                <td>{{ i.paymentmode_id }}</td>
                <td>{{ i.redeem_date }}</td>
                <td><a class="btn btn-success" href="../success/{{ i.id }}">Success</a>&nbsp;<a class="btn btn-danger" href="../cancel/{{ i.id }}">Cancel</a></td>
            </tr>
            {% endfor %}
        </tbody>
</tbody>

    </table>
</div>

<div class="">
<table id="alluser" class="display nowrap" style="width:100%">
        <thead>
            <tr>
                <th>No.</th>
                <th>Refer Code</th>
                <th>Username</th>
                <th>Email</th>
                <th>Password</th>
                <th>Status</th>
                <th>Block Status</th>
                <th>Referred By</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in alluser %}
            <tr>
                <td></td>
                <td>{{ user.refercode }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.is_active }}</td>
                <td>{{ user.is_block }}</td>
                <td>{{ user.referredby }}</td>
                <td><a class="btn btn-success" href="../block/{{ user.id }}">Block User</a></td>



            </tr>
            {% endfor %}
        </tbody>
</tbody>

    </table>
</div>

{% endblock %}

clicknetapp/templates/html/dashboard.html
{% extends 'html/header.html' %}

{% block head %}


{% load static %}

<title>Dashboard</title>
{% endblock %}

{% block body %}


    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Dashboard</h4>

            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Sales Cards  -->
        <!-- ============================================================== -->
                <div class="row">

             <!-- Column -->
            <div class="col-md-12 col-lg-12 col-xlg-12">
                <div class="card">

                    <div class="box text-center" style="padding: 30px 0 50px 0;">
                            <h3 class="text-black" style="padding: 5px;" >Short Your Url</h3>
                       <div id="hidethis" style="display: unset;">

                            <form method="POST" id="shortenadmin">
                        <input style="border: none;
                        border-radius: 20px;
                        background: rgba(154, 209, 144, 0.637);
                        padding: 10px;
                        width: 80%;
                        " type="url" pattern="https?://.+" placeholder="Enter Your Url" name="url" id="url" autocomplete="off" required/>
                        <label id="error" style="margin: 10px ;
                        border-radius: 20px;
                       color: #D8000C;
                       line-height: 40px;
                       text-align: center;
                       width: 80%;
                    background-color: #FFD2D2;"></label><br/>
                        <button class="btn btn-success btn-sm" style="margin: 10px;padding: 10px;" id="submitadmin" type="submit">Short Url</button>
                        </form>
                        </div>

                        <div id="showthis" style="display: none">
                            <div id="showadmin">
                             <input style="border: none;
                        border-radius: 20px;
                        background: rgba(154, 209, 144, 0.637);
                        padding: 10px;
                        width: 80%;
                        " type="url" pattern="https?://.+" id="surl" readonly placeholder="Enter Your Url" name="url" required/>
                        <br/>
                        <label id="error1" style="margin: 10px ;
                        border-radius: 20px;
                       color: #D8000C;
                       line-height: 40px;
                       text-align: center;
                       width: 80%;
                    background-color: #FFD2D2;"></label><br/>
                        <button onclick="copy()" class="btn btn-success" id="copyme" onmousemove="hidetoltip()" ><i class=" fa fa-copy " style="font-size:32px;padding: 0px;color:white;"></i></button>
                        <a class="btn btn-success btn-sm" id="short_another" style="text-align: right; margin: 5px;padding: 10px;color:white;" onclick="short_another()">Short Another Url</a>
                        <br/>

                           </div>
                        </div>

                    </div>
                </div>
            </div>


        </div>
                <!-- ============================================================== -->
                <!-- Sales chart -->
                <!-- ============================================================== -->
<div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-md-flex align-items-center">
                                        <div style="text-align:center;">
                                                <caption><h1 >Your Short Url List</h1></caption><br/>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
<div >

    <form id="geturlform" style="display:none"  method="POST">

   <input type="submit" value="Refresh">
 </form>

     <div id="forTable">
</div>
<div id="loading-image" class="container text-center"><img style="width:100px; height:100px;" src="/static/img/ajaxloader.gif"/></div>


</div>
<br/><br/><br/>
<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="d-md-flex align-items-center">
                                    <div>
                                        <h4 class="card-title">Overview Analysis</h4>
                                        <h5 class="card-subtitle">Overview of Your Account</h5>
                                    </div>
                                </div><br/>
                                <div class="row">
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-cyan text-center">
                                {% if totalclicks is None %}
                                <h3 class="text-white">0</h3>
                                {% else %}
                                <h3 class="text-white">{{ totalclicks }}</h3>
                                {% endif %}
                                <h6 class="text-white">Total Click</h6>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-info text-center">
                                {% if clickearning is None %}
                                <h3 class="text-white">0</h3>
                                {% else %}
                                <h3 class="text-white">{{ clickearning|floatformat:2 }}</h3>
                                {% endif %}
                                <h6 class="text-white">Earning Through Clicks</h6>
                            </div>
                        </div>
                    </div>
                     <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-success text-center">
                                {% if blc is None %}
                                <h3 class="text-white">0</h3>
                                {% else %}
                                <h3 class="text-white">{{ blc|floatformat:2 }}</h3>
                                {% endif %}
                                <h6 class="text-white">Wallet Balance</h6>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-danger text-center">
                                {% if lifetimeearning is None %}
                                <h3 class="text-white">0</h3>
                                {% else %}
                                <h3 class="text-white">{{ lifetimeearning|floatformat:2 }}</h3>
                                {% endif %}
                                <h6 class="text-white">Lifetime Earning</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-warning text-center">
                                {% if totalredeem is None %}
                                <h3 class="text-white">0</h3>
                                {% else %}
                                <h3 class="text-white">{{ totalredeem|floatformat:2 }}</h3>
                                {% endif %}
                                <h6 class="text-white">Total Withdrawal</h6>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-danger text-center">
                                {% if redeempanding is None %}
                                <h3 class="text-white">0</h3>
                                {% else %}
                                <h3 class="text-white">{{ redeempanding|floatformat:2 }}</h3>
                                {% endif %}
                                <h6 class="text-white">Panding Withdrawal</h6>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-cyan text-center">
                                {% if redeemsuccess is None %}
                                <h3 class="text-white">0</h3>
                                {% else %}
                                <h3 class="text-white">{{ redeemsuccess|floatformat:2 }}</h3>
                                {% endif %}
                                <h6 class="text-white">Success Withdrawal</h6>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <div class="col-md-6 col-lg-3 col-xlg-3">
                        <div class="card card-hover">
                            <div class="box bg-info text-center">
                                <h3 class="text-white">{{ referblc|floatformat:2 }}</h3>
                                <h6 class="text-white">Referral Earning</h6>
                            </div>
                        </div>
                    </div>
                </div>
                            </div>
                        </div>
                    </div>
                </div>



<br/><br/>


                                                <canvas id="myChart" style="width:100%;height: 400px;"></canvas>
<br/><br/>








                    <!-- ============================================================== -->
                    <!-- Recent comment and chats -->
                    <!-- ============================================================== -->
                </div>
                <!-- ============================================================== -->
                <!-- End Container fluid  -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- footer -->
                <!-- ============================================================== -->
                <footer class="footer text-center">
                        All Rights Reserved by <a href="https://wrappixel.com">Click.net</a>.
                    </footer>
                <!-- End footer -->
                <!-- ============================================================== -->
            </div>


{% endblock %}

clicknetapp/templates/html/myteam.html
{% extends 'html/header.html' %}
{% block head %}
<title>My Team</title>
{% endblock %}

{% block body %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="d-md-flex align-items-center">
                    <div>
                            <caption><h1 style="text-align:center">Your Referral Team</h1></caption><br/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<table id="example" class="display nowrap" style="width:100%">
        <thead>
            <tr>
                <th style="text-align:center">No.</th>
                <th style="text-align:center">Referral User</th>
                <th style="text-align:center">Referral Earnings</th>
            </tr>
        </thead>
        <tbody>
            {% for i in team %}
            <tr>
                <td style="text-align:center"></td>
                <td style="text-align:center">{{ i.username }}</td>
                {% for j in i.balance_set.all %}
                <td style="text-align:center">{{ j.referbyblc }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
</tbody>

    </table>
    </div>
{% endblock %}